# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-05 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
